"use client";
import {useEffect,useState} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import * as Tabs from "@radix-ui/react-tabs";
import * as Accordion from "@radix-ui/react-accordion";
import * as Switch from "@radix-ui/react-switch";
import * as Slider from "@radix-ui/react-slider";
import Image from "next/image";

const items=["Button","Input","Select","Dialog","Tabs","Accordion","Switch","Slider","Badge","Alert","Table","Navigation"];
function Mark(){return <span className="mark" aria-hidden>T</span>}
function Command({children}:{children:string}){const[c,setC]=useState(false);return <button className="command" onClick={()=>{navigator.clipboard?.writeText(children);setC(true);setTimeout(()=>setC(false),1400)}} aria-label={`Copy ${children}`}><code>{c?"Copied to your garden":children}</code><span>{c?"✓":"Copy"}</span></button>}
function WindowDialog(){const[open,setOpen]=useState(false);return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className={`window-trigger ${open?"is-open":""}`} aria-label="Open the villa window demonstration"><span className="window-glow"/><span className="shutter left"/><span className="window-view">Enter</span><span className="shutter right"/></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><span className="eyebrow">Illustrated component · 01</span><Dialog.Title>Window Dialog</Dialog.Title><Dialog.Description>The architecture is the trigger. Real focus management and keyboard behavior live beneath the drawing.</Dialog.Description><Command>npx shadcn@latest add mkeresty/toile/window-dialog</Command><Dialog.Close className="text-button">Close the shutters</Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>}
function Hero(){return <section className="hero" id="top"><header className="nav"><a href="#top" className="brand"><Mark/><span>TOILE</span></a><nav aria-label="Primary"><a href="#story">Manifesto</a><a href="#components">Components</a><a href="#install">Install</a><a href="https://github.com/mkeresty/toile">GitHub ↗</a></nav></header><div className="hero-copy draw-in"><span className="issue">Issue № 01 · An open-source React library</span><h1>The interface<br/><em>is</em> the illustration.</h1><p>Source-owned components where editorial drawing, semantic HTML, and restrained motion become one object.</p><div className="hero-actions"><a href="#install" className="button primary">Begin with Toile</a><a href="#scene" className="button ghost">Open the window ↓</a></div></div><div className="hero-art" aria-label="An engraved Mediterranean lakeside village"><Image src="/mediterranean-scene.png" alt="Cobalt engraving of a Mediterranean villa and lakeside village" width={1672} height={940} priority/><div className="window-anchor"><WindowDialog/></div><span className="bird bird-one" aria-hidden>⌁</span><span className="bird bird-two" aria-hidden>⌁</span></div><p className="plate-caption">Plate I — The window belongs to the interface.</p></section>}
function Botanical(){const[alive,setAlive]=useState(true);const[value,setValue]=useState([62]);return <section className={`botanical ${alive?"alive":"still"}`} id="components"><div className="section-heading"><span className="folio">02</span><div><span className="eyebrow">The collection</span><h2>Useful, before it is beautiful.</h2><p>Core controls have an editorial character of their own. Illustration is an additional capability—not a dependency.</p></div></div><div className="specimen-grid"><article className="specimen controls"><div className="specimen-head"><span>FIELD STUDY</span><span>CORE / FORM</span></div><label>Email address<input type="email" placeholder="studio@example.com"/></label><label>Field notes<textarea placeholder="Write an observation…" rows={3}/></label><div className="control-row"><label className="switch-label">Ambient growth <Switch.Root className="switch" checked={alive} onCheckedChange={setAlive}><Switch.Thumb/></Switch.Root></label><button className="button primary">Submit specimen</button></div><div className="plant" aria-hidden><i/><i/><i/><i/><i/></div></article><article className="specimen instrument"><div className="specimen-head"><span>CELESTIAL INDEX</span><span>ILLUSTRATED / CONTROL</span></div><div className="astrolabe" style={{"--dial":`${value[0]*2.4}deg`} as React.CSSProperties}><div className="orbit o1"/><div className="orbit o2"/><div className="needle"/><span>✦</span></div><label>Orbital inclination <strong>{value[0]}°</strong><Slider.Root className="slider" value={value} onValueChange={setValue} max={90}><Slider.Track><Slider.Range/></Slider.Track><Slider.Thumb aria-label="Orbital inclination"/></Slider.Root></label><p>Component state turns the mechanism. The control remains a native, accessible slider.</p></article></div></section>}
function Index(){return <section className="index" id="story"><div className="section-heading inverse"><span className="folio">03</span><div><span className="eyebrow">A working system</span><h2>From quiet primitives<br/>to complete worlds.</h2></div></div><Tabs.Root defaultValue="core" className="library-tabs"><Tabs.List aria-label="Library tiers"><Tabs.Trigger value="core">I. Core</Tabs.Trigger><Tabs.Trigger value="illustrated">II. Illustrated</Tabs.Trigger><Tabs.Trigger value="scenes">III. Scenes</Tabs.Trigger></Tabs.List><Tabs.Content value="core"><div className="component-list">{items.map((c,i)=><a key={c} href="#install"><span>{String(i+1).padStart(2,"0")}</span>{c}<small>View specimen ↗</small></a>)}</div></Tabs.Content><Tabs.Content value="illustrated"><div className="editorial-copy"><h3>Controls with a physical presence.</h3><p>Windows open, branches bend, cabinets unfold, and instruments turn—while the underlying interface stays semantic and accessible.</p><Command>npx shadcn@latest add mkeresty/toile/window-dialog</Command></div></Tabs.Content><Tabs.Content value="scenes"><div className="editorial-copy"><h3>Compose depth, not decoration.</h3><p>Layer artwork and HTML through semantic anchors. Public scene primitives manage depth, pointer behavior, motion preference, and responsive recomposition.</p><Command>npx shadcn@latest add mkeresty/toile/mediterranean-scene</Command></div></Tabs.Content></Tabs.Root></section>}
function Docs(){return <section className="docs" id="install"><div className="docs-intro"><span className="eyebrow">Open source · Source owned</span><h2>Add one piece.<br/>Keep every line.</h2><p>Install only the files you need. Change the ink, recompose the art, or rewrite the motion. Toile stays in your codebase—not ours.</p><Command>npx shadcn@latest add mkeresty/toile/button</Command></div><Accordion.Root type="single" collapsible defaultValue="i1" className="accordion"><Accordion.Item value="i1"><Accordion.Header><Accordion.Trigger>01 / Install a primitive <span>+</span></Accordion.Trigger></Accordion.Header><Accordion.Content><pre><code>{`import { Button } from "@/components/toile/button"\n\n<Button variant="ink">Open the folio</Button>`}</code></pre></Accordion.Content></Accordion.Item><Accordion.Item value="i2"><Accordion.Header><Accordion.Trigger>02 / Tune the art direction <span>+</span></Accordion.Trigger></Accordion.Header><Accordion.Content><p>Semantic paper, ink, line, detail, density, and motion tokens create distinct editions without losing coherence.</p></Accordion.Content></Accordion.Item><Accordion.Item value="i3"><Accordion.Header><Accordion.Trigger>03 / Compose a scene <span>+</span></Accordion.Trigger></Accordion.Header><Accordion.Content><p>Layer distant, middle, interface, and foreground planes. Anchors allow real controls to occupy meaningful places in the drawing.</p></Accordion.Content></Accordion.Item></Accordion.Root></section>}
export default function Home(){useEffect(()=>{document.documentElement.classList.add("ready")},[]);return <main><Hero/><Botanical/><Index/><Docs/><footer><div><Mark/><span>TOILE</span></div><p>Interfaces, drawn into being.</p><nav><a href="#top">Top ↑</a><a href="https://github.com/mkeresty/toile">Source ↗</a></nav><small>Open source · MMXXVI</small></footer></main>}
